spring:
  application:
    name: DATA-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://covid-19-service-registry.herokuapp.com/
  instance:
    hostname: localhost